# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
